//Auth Action Types
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const CHANGE_STUDENT_REGISTRATION_FORM = 'CHANGE_STUDENT_REGISTRATION_FORM';
export const CHANGE_EDUCATOR_REGISTRATION_FORM = 'CHANGE_EDUCATOR_REGISTRATION_FORM';
