//Ajax action types
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_ERROR = 'AJAX_ERROR';

//Auth Action Types
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const CHANGE_STUDENT_REGISTRATION_FORM = 'CHANGE_STUDENT_REGISTRATION_FORM';
export const CHANGE_EDUCATOR_REGISTRATION_FORM = 'CHANGE_EDUCATOR_REGISTRATION_FORM';
    //Asynchronous Persist Login ACtion Types.
export const PERSIST_LOGIN = 'PERSIST_LOGIN';
export const PERSIST_LOGOUT = 'PERSIST_LOGOUT';


//Tutorial Action Types 
export const CHANGE_CREATE_TUTORIAL_FORM = 'CHANGE_CREATE_TUTORIAL_FORM';
export const CHANGE_UPDATE_TUTORIAL_FORM = 'CHANGE_UPDATE_TUTORIAL_FORM';
//Asynchronous TUtorial Action Types.
    //Asynchronous General Tutorial Action Types
export const GET_GENERAL_TUTORIALS_SUCCESS = 'GET_GENERAL_TUTORIALS_SUCCESS';

//User Action Types.
//Asynchronous User Action Types.
    //Asynchronous General User ACtion Types.
export const GET_GENERAL_EDUCATORS_SUCCESS = 'GET_GENERAL_EDUCATORS_SUCCESS';
export const GET_GENERAL_STUDENTS_SUCCESS = 'GET_GENERAL_STUDENTS_SUCCESS';

//Criticism Action Types
export const CHANGE_CREATE_TUTORIAL_CRITICISM_FORM = 'CHANGE_CREATE_TUTORIAL_CRITICISM_FORM';
export const CHANGE_CREATE_EDUCATOR_CRITICISM_FORM = 'CHANGE_CREATE_EDUCATOR_CRITICISM_FORM';
export const CHANGE_UPDATE_TUTORIAL_CRITICISM_FORM = 'CHANGE_UPDATE_TUTORIAL_CRITICISM_FORM';
export const CHANGE_UPDATE_EDUCATOR_CRITICISM_FORM = 'CHANGE_UPDATE_EDUCATOR_CRITICISM_FORM';
//Asynchronous Criticism Action Types 
    //Asynchronous TUtorial Criticism Action Types.
export const GET_TUTORIAL_CRITICISMS_SUCCESS = 'GET_TUTORIAL_CRITICISMS_SUCCESS';
    //Asynchronous Educator Criticism Action Types
export const GET_EDUCATOR_CRITICISMS_SUCCESS = 'GET_EDUCATOR_CRITICISMS_SUCCESS';

//Programming Languages Action Types.
export const GET_PROGRAMMING_LANGUAGES_SUCCESS = 'GET_PROGRAMMING_LANGUAGES_SUCCESS';