// import { StyleSheet } from 'react-native';

export const errorColor = 'red';
export const successColor = 'green';
export const buttonColor = '#19198C';
export const buttonTextColor = '#F2F2F2';
export const buttonTextSize = 18;
export const lineHeight = 18;
export const headerTextWeight = 'bold';
export const headerTextSize = 24;
export const textColor = "#FFFFFF";
export const textHeight = 15;
export const textSize = 17;
export const navTextColor = '#FDF4F4';
export const navBackgroundColor = '#19198C';
export const mainColor = '#19198C';
export const inputColor = '#FFFFFF';
export const inputBorderRadius = 30;
export const inputFontSize = 14;
export const appBackgroundColor = '#000000';